theme: jekyll-theme-minimal
title: Ugent Heat Stress Measurement campaign @ Antwerp 10 Miles 2026
description: We are conducting a heat stress measurement campaign during the Antwerp 10 Miles 2026. This research is led by the University of Ghent with practical assistance from GOLOZA the organizer.
logo: /figures/logo_UGent_NL_RGB_2400_kleur.png
