theme: jekyll-theme-minimal
title: Ugent Heat Stress Measurement campaign @ Antwerp 10 Miles 2026
description: This research is led by the University of Ghent with practical assistance from GOLAZO.
logo: /figures/logo_UGent_NL_RGB_2400_kleur.png
